name: Playwright test with Allure HTML Report

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: ['*']
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  run-tests:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.52.0-noble

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: latest
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies
        run: |
          poetry install --extras dev
          poetry run playwright install --with-deps

      - name: Run tests with Allure
        run: |
          poetry run pytest --alluredir=allure-results
        continue-on-error: true

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@v1.12
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          allure_report: allure-report
          gh_pages: gh-pages
          allure_history: allure-history

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        if: always()
        with:
          path: allure-report

  deploy:
    needs: run-tests
    runs-on: ubuntu-latest
    name: Deploy to GitHub Pages
    if: always()

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4